// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeBook.Context;

#nullable disable

namespace RecipeBook.Migrations
{
    [DbContext(typeof(EFContext))]
    partial class EFContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeBook.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Steps")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RecipesTBL");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ingredients = "[\"1 white onion (halved and sliced)\",\"3 garlic cloves (diced)\",\"4 golden sweet potatoes (halved and sliced)\",\"2 large carrots (sliced into rounds)\",\"1 jalapeno (diced)\",\"1 tomato (diced)\",\"1-2 TBS butter or coconut oil\",\"Apple cider vinegar\",\"1 TBS horseradish powder\",\"1 TBS Better than bouillon adobo\",\"1 tsp dried basil\",\"~ 3qts of water\",\"1 can coconut milk\",\"Salt and pepper\"]",
                            Name = "Sweet potato soup",
                            Notes = "[\"If you want a more savory soup- \\r\\nUse regular potatoes \\r\\nAdd 1/4 tsp ground fennel seed \\r\\nAdd sliced celery\\r\\nLeave out the coconut milk.\\r\\nAfter the soup is done cooking, remove from heat and immediately stir in 1 cup of heavy cream.\"]",
                            Steps = "[\"In a 6 qt stock pot (with lid), use butter or coconut oil to saute onion and garlic cloves for about 5 minutes.\",\"Add horseradish powder and stir until\",\"It has absorbed the oil.\",\"Deglaze using a splash of apple cider vinegar.\",\"Add water.\",\"Add sweet potatoes, carrots, jalapenos, tomato, and basil.\",\"Stir in bouillon and coconut milk.\",\"Bring to a simmer and cover for about 45 minutes, stirring occasionally.\",\"Should be good once you can smash a potato pretty easy with your spoon.\",\"Salt and pepper to taste!\"]"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
